server:
    port: 2222
spital:
    rabbitmq:
        exchange: spital.exchange
        queue: spital.consultqueue
        routingkey: spital.routingkey
spring:
    application:
        name: notification-service
    data:
        mongodb:
            database: administrativ
            uri: mongodb://127.0.0.1:27017/administrativ
            version: 4.4.6
    main:
        allow-bean-definition-overriding: true
    rabbitmq:
        host: localhost
        password: guest
        port: 5672
        username: guest
    cloud:
        discovery:
            enabled: true

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
    instance:
        hostname: localhost
